name: Contacts (CI/CD)

on:
  pull_request:
    branches:
      - main
    # paths:
    #   - "apps/contacts/**"
  push:
    branches:
      - main
    # paths:
    #   - "apps/contacts/**"

env:
  NODE_VERSION: '22'
  SERVICE: 'contacts'

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install PNPM
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint --filter=${{ env.SERVICE }}

  check-types:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install PNPM
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check types
        run: pnpm run check-types --filter=${{ env.SERVICE }}

  # tests:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v5
  #     - name: Install PNPM
  #       uses: pnpm/action-setup@v4
  #     - name: Use Node.js ${{ env.NODE_VERSION }}
  #       uses: actions/setup-node@v5
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}
  #         cache: "pnpm"

  #     - name: Install dependencies
  #       run: pnpm install --frozen-lockfile

  #     - name: Test
  #       run: pnpm run test:coverage --filter=${{ env.SERVICE }}

  build:
    runs-on: ubuntu-22.04
    needs: [lint, check-types]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build --filter=${{ env.SERVICE }}
        

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SERVICE }}
          path: apps/${{ env.SERVICE }}/build
          retention-days: 1
      